export enum ROUTES {
  HOME_TABS = 'HOME_TABS',
  LOGIN = 'LOGIN',

  // Tabs Navigation ......
  DIRECTION1 = 'DIRECTION1',
  DIRECTION2 = 'DIRECTION2',
  DIRECTION3 = 'DIRECTION3',
  DIRECTION4 = 'DIRECTION4',
  DIRECTION5 = 'DIRECTION5',
  DIRECTION6 = 'DIRECTION6',
  DIRECTION7 = 'DIRECTION7',
  DIRECTION1_STACK = 'DIRECTION1_STACK',
}
